### ISSUE TITLE
Allow users a read-only view of notebook when Leo is down

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/terra-ui#1003]
Leo has been very flakey recently and even though I am an owner on a workspace, I am getting an error that I cannot run analyses on a notebook. This is caused by Leo flakiness which Terra should be more resilient to. I cannot even view the notebook.
<img width="1145" alt="screen shot 2018-12-13 at 11 36 58 am" src="https://user-images.githubusercontent.com/2395211/49954061-87821480-fecd-11e8-90f1-9f541df2391b.png">

When Leo is not responding but a user has access to a notebook as an Owner, Reader, Writer, etc, we should automatically load a Read-Only version (with Calhoun). Then once Leo is back up and they have clusters and if the user has  Owner/Writer access, ask them if they want to edit the notebook.

**Comment by bradtaylor** [comment]
@katevoss Will this be fixed by #1085?

**Comment by katevoss** [comment]
I'll make sure it is fixed in that issue, yes!

**Comment by katevoss** [comment]
Re-opening this as I did not complete it as a part of #1085

**Comment by katevoss** [comment]
I suspect that this is fixed now given that if Leo doesn't respond, we still call Calhoun to render the preview.
