### ISSUE TITLE
Minor issue: 1/1 in notification window

### ISSUE THREAD

**Issue by seanhorgan** [DataBiosphere/terra-ui#1022]
![screenshot 2018-12-19 at 10 42 48 pm](https://user-images.githubusercontent.com/428857/50262966-91ca7400-03e1-11e9-8f5a-b98271843392.png)

Minor issue: when Terra displays a single notification, it tells me that it's 1/1. This chews up real-estate that's better spent displaying the actual message.

**Comment by katevoss** [comment]
Given that we have updated our notifications to fly-in banners, I believe this is resolved. @seanhorgan feel free to reopen if you still see this behavior.
