### ISSUE TITLE
Rerun job failures for single-workflow submissions

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/terra-ui#1045]
Currently, we only provide the option to re-run failed workflows if a submission contains >1 workflow. We should provide this option even if this submission contained a single workflow (as is common when users are trying things out and debugging).

In this case there is no need to create a new set out of the failed entities- just launch a new workflow with the original entity.

**Comment by breilly2** [comment]
Release notes: In Job History, "Re-run failures" is now available for submissions with a single job.

(Not 100% sure that "submission" and "job" are the currently preferred terms for these concepts)
