### ISSUE TITLE
expanding data column to view entire text under Tables

### ISSUE THREAD

**Issue by schaluva** [DataBiosphere/terra-ui#1052]
The text under Tables in the Data tab is not fully visible. The text following "participant (3500)" for example, gets cut off as shown in the attached screenshot.

![](https://broadinstitute.zendesk.com/attachments/token/mobs6s08QqBs7UQPx0i8GzTNJ/?name=Screen+Shot+2019-01-09+at+6.05.46+PM.png)

**Comment by katevoss** [comment]
Closing this as the text is now fully visible:
<img width="279" alt="Screen Shot 2019-05-14 at 9 22 25 AM" src="https://user-images.githubusercontent.com/2395211/57701350-d1605980-7629-11e9-9939-e1dacc469362.png">
