### ISSUE TITLE
Remove free-credit-billing-account once a user is Terminated in the free trial

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/terra-ui#1063]
When a user is terminated from the free trial, whether they have used up their free credits or they have expired, the user still has the free-credits-billing-account in their list. When I tried to create workspace I got a spinner for a long time then eventually this message:

![Screen Shot 2019-01-14 at 4.10.52 PM.png](https://images.zenhubusercontent.com/580fc01f95e42b6c5bab0c94/b656ea10-4227-4a68-b987-7bfbdcf9667e)

We should remove this so that users don't try to use it to create workspaces. 

Also, in workspaces that the user already created using the free-trial-billing-account, we should have a better messaging/experience for when a user tries to start a cluster or create a notebook.

![Screen Shot 2019-01-14 at 4.14.54 PM.png](https://images.zenhubusercontent.com/580fc01f95e42b6c5bab0c94/9c3aadb3-d0fc-44d7-b325-b75e5e98f34f)

Even though I don't have write access, the Notebook launcher is still active:
![Screen Shot 2019-01-14 at 4.15.07 PM.png](https://images.zenhubusercontent.com/580fc01f95e42b6c5bab0c94/1236d875-6614-4818-aab0-8536b1f007b9)

![Screen Shot 2019-01-14 at 4.15.26 PM.png](https://images.zenhubusercontent.com/580fc01f95e42b6c5bab0c94/f1a3d20e-3eaf-4265-ace7-b7f870185c54)

**Idea**: after Free Trial Termination, workspaces created with the free-trial-billing-account sets all users to Reader? I believe we already have a good UX for readers.

related to #1055

**Comment by bradtaylor** [comment]
I believe there is a way under the hood to move the free credits project to a new billing account. I think that's the way we'd like to solve this

**Comment by katevoss** [comment]
This will be solved by #1186, closing.
