### ISSUE TITLE
Left sidebar build date is at the bottom when a user has many workspaces

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/terra-ui#1082]
When a user has many workspaces and they open the left sidebar, the Terra Build Date is pushed all the way to the bottom of the scroll for workspaces:
![Screen Shot 2019-01-17 at 2.10.48 PM.png](https://images.zenhubusercontent.com/580fc01f95e42b6c5bab0c94/e0fcc631-1fcd-407d-a306-2934fc93cb34)

This is a side effect of the changes made in https://github.com/DataBiosphere/saturn-ui/pull/1055 to fix the sidebar length

**Comment by panentheos** [comment]
This is the expected placement of this given the new layout. Closing for now, pending a larger design pass of the nav bars.
