### ISSUE TITLE
Fix UX for cluster creation when a notebook is clicked

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/terra-ui#1089]
Cluster autocreation has been turned off in Terra. A new user comes in. They clone a workspace. Hey look, a notebook. They click on it.

At the top of the page there should be a message
"You are viewing this notebook in a read-only mode. Would you like to create a notebooks runtime to edit and run this notebook?" clicking 'create' should bring up the a view of the widget to select size.

Below this message should be the read-only view of the notebook.

If the user has a notebook that is 'creating', we should message that this may take 5-10 minutes, and that they are welcome to nav away and come back.

If a user has a notebook in 'creating' or 'starting', then in place of the message above we should display the status as a series of steps organized horizontally, similar to how All of US is displaying this.

**Comment by katevoss** [comment]
AoU's mockup design:
<img width="1241" alt="screen shot 2019-01-22 at 2 23 41 pm" src="https://user-images.githubusercontent.com/2395211/51560052-7d025580-1e51-11e9-8c82-b03c523916da.png">

**Comment by katevoss** [comment]
To clarify the AC:

- [ ] When a cluster is creating, then user sees message in first box that says something like "Creating notebook runtime environment. You can navigate away and return in 5-10 minutes."
- [ ] When a cluster is starting, a user sees a message in the first box that says something like "Starting notebook runtime environment, this may take up to 2 minutes."

**Comment by katevoss** [comment]
From #898, adding AC:
- [ ] Add similar UX to Terminal for when a Cluster is creating
- [ ] Make the Terminal icon clickable, even if the cluster is stopped. Clicking the terminal icon will start the cluster.
- [ ] Add tooltip/notice to user when they can't use the Terminal so they don't have write permissions

**Comment by kleighwe** [comment]
@zarsky-broad can you toss an estimate on this when you get a chance? :) Thanks!
