### ISSUE TITLE
free trial banner appears when not whitelisted

### ISSUE THREAD

**Issue by elizzhao** [DataBiosphere/terra-ui#1091]
discovered when fiddling around with creating new users after the banner prod deploy--even when a user is not on the whitelist, the banner appears

AC: Link and banner do not appear for non-whitelisted users.

**Comment by elizzhao** [comment]
The banner also appears on the "could not display workspace" page if a user is logged in and directly navigates to a workspace they do not have access to.

**Comment by panentheos** [comment]
Since the whitelist is going away soon, I don't think this is worth fixing.
