### ISSUE TITLE
Problem configuring a notebook to use a Spark cluster

### ISSUE THREAD

**Issue by dglazer** [DataBiosphere/terra-ui#1098]
When I try to reconfigure the notebook VM runtime environment, and click on the "Configure as Spark cluster" checkbox, the UI closes and doesn't let me finish setting up my new configuration. 

Before clicking the Spark checkbox:
![image](https://user-images.githubusercontent.com/5824733/51508584-e5a2f100-1dc3-11e9-850f-0eeb3baa7da7.png)
After clicking the Spark checkbox:
![image](https://user-images.githubusercontent.com/5824733/51508599-f94e5780-1dc3-11e9-8a4b-c12ae7fa47ec.png)

**Comment by katevoss** [comment]
Hi @dglazer, I'm not able to reproduce this issue when you are setting up a Spark cluster. Are you still experiencing unable to configure a new Spark cluster in this workspace? Would you mind trying to set up a Spark cluster in a different workspace under a different billing project? If that is successful you can shut it down afterward.

**Comment by dglazer** [comment]
Update -- it looks like this is related to #1093 -- if I scroll so that the banner described there is off-screen, then the issue described here goes away. (@dmohs who was sitting next to me when we reproduced it)

**Comment by katevoss** [comment]
@dglazer is this still an issue now that the Free Credits banner is dismissible?

**Comment by dglazer** [comment]
It's not a blocking issue for me, since I can just get rid of the banner.
Up to you all if it's worth tracking down to avoid breakage for people who
don't dismiss the banner, or for any future top-of-page stuff we add.

**Comment by zarsky-broad** [comment]
This actually appears to happen whenever there isn't enough height in the window to show the popup. @panentheos thoughts?

**Comment by panentheos** [comment]
Yeah, this is an issue with the positioning of the popup. I think we should consider making it a modal, since it's so large/complex. We had discussed this a while back, I think.
