### ISSUE TITLE
Workspace-relative links and workspace variables in Workspace Descriptions

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/terra-ui#1102]
The workspace description can empower Terra users to organize their workspaces as they want them. Today, the ability to include links to notebooks, data in GCS, and data in Google BigQuery, is very powerful.

There are a few features that would make this more powerful:

- allow links to be workspace-relative (for example to notebooks), and/or
- enable references to workspace properties such as the workspace name, workspace bucket, and workspace attributes

Links in the description today are treated as site-relative. So if I put in a link URL of:

- `notebooks/launch/my_notebook.ipynb`

it gets enabled as:

- `https://app.terra.bio/notebooks/launch/my_notebook.ipynb`

It would be great if it were rendered as:

- `https://app.terra.bio/#workspaces/my-project/my-workspace/notebooks/launch/my_notebook.ipynb`

I can hard-code this full path in the workspace description, but I'd like for the URL to be workspace-relative for cloned workspaces.

An alternative to changing the rendering would be to provide some way of referencing the workspace project and name. With that I could construct the full URL myself and then cloned workspaces would provide the right links too.

**Comment by kleighwe** [comment]
Great idea, but we won't be able to act on it for awhile. Closing as "wont fix" but do speak up if the problem persists!

**Comment by mbookman** [comment]
Made this a Feature Request:
https://support.terra.bio/hc/en-us/community/posts/360044300192-Workspace-relative-links-and-workspace-variables-in-Workspace-Descriptions
