### ISSUE TITLE
Display the path to the Google bucket on the workspace dashboard

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/terra-ui#1108]
On the workspace "Dashboard" page, we display a link to the Google Bucket, but we don't actually display the path to the bucket to the user. I was not able to find anywhere in the Terra UI where we actually display the path to the bucket. Instead I have to click on the link and go to the bucket in the Google Console. Then I can grab the bucket name.

I noticed this because I provided a sample notebook to a collaborator which shows how to read and write the workspace bucket. The path in the sample notebook was for a different workspace. I think there are too many steps to the instructions I needed to give him to find the bucket name for his workspace, and I think if we displayed the bucket name I probably would not have needed to give any instructions. It would have been self-discoverable.

Discussion: We want a button to copy this to the clipboard on dashboard and on the data tab itself.

**Comment by dglazer** [comment]
Implementation thoughts:
- could display the bucket path (as Matt suggests)
- could display a "copy path to clipboard" affordance, w/o actually displaying the path until clicked
- could combine into one -- e.g. when you click on today's "Google bucket" link, it pops up a small dialog that a) displays the bucket path  b) says "already copied to clipboard"  c) has a link to the GCS console

**Comment by schaluva** [comment]
Also have received input from multiple users for atleast the bucket hash visible or easy to copy without having to click into the physical bucket browser
