### ISSUE TITLE
Error hit opening left-hand hamburger menu

### ISSUE THREAD

**Issue by danxmoran** [DataBiosphere/terra-ui#1114]
@adkinsrs tried to expand the left-hand menu to log into Terra, and the page crashed with:
<img width="1440" alt="screen shot 2019-01-25 at 1 37 47 pm" src="https://user-images.githubusercontent.com/2755881/51767040-352a3b00-20aa-11e9-9c08-8cafbcd91567.png">

**Comment by bradtaylor** [comment]
Hi @danxmoran, sorry for the delayed followup. Have you seen this issue recur?

**Comment by adkinsrs** [comment]
@bradtaylor I was the one who reported this to @danxmoran and fortunately I have not seen this issue reoccur since.

**Comment by katevoss** [comment]
@adkinsrs if you see this issue pop up again, let us know!
