### ISSUE TITLE
FR: Add "backup notebooks" and/or source control integration

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/terra-ui#1117]
The Terra environment provides a very nice place for researchers to get started with running notebooks. No need to install anything on my workstation or laptop.

However management of notebooks is currently do-it-yourself, in that there is no source control integration or history of changes saved; just the latest edits saved to Cloud Storage.

It would be great to have some automated features to help researchers avoid lost work. As an interim solution, we have notebooks that we can run to back up our notebooks (`gsutil cp <bucket- path>/notebooks <bucket-path>/backups/<datestamp>`).

It would be great if we could have something like this built into the platform or have integration with source control systems. One option is to use Google [Cloud Source Repositories](https://cloud.google.com/source-repositories/). This is a private git repository. Using this would mirror the existing solution of storing notebooks in a Google bucket. Just like having a bucket associated with a workspace, there could be a repo associated with a workspace and access controlled the same way.

**Comment by kleighwe** [comment]
This is on our minds for the distant future. We're going to close for board cleaning reasons, please file a feature request on the forum if this is still something desired!
