### ISSUE TITLE
FR: Enable data providers to publish their own Featured workspaces.

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/terra-ui#1118]
When a data provider makes data available through Terra, they will want to provide getting started code and documentation to go with it. The current mechanism is that they can share these workspaces with researchers, and the workspaces show up in the researchers Workspaces tab.

This is an awesome capability, but is also likely to produce clutter in a researchers workspace list. It is also not really easy to tell who the true owner of the workspace is and whether it is either official or legitimate.

It would be great if there were a way to tag workspaces such that an end user can go to the "Feature Workspaces", select the data provider they are interested in, and see a list of available workspaces.

A particular provider might have a set of workspaces, each for handling a different data type. If I don't know how to work with genomic or transcriptomics data, I might only want the workspace for how to work with clinical data. Or I might want the workspace that gives examples of working with R notebooks versus Python.

**Comment by bradtaylor** [comment]
We allow users to make their workspaces public, and we can provide some more searchability on these. For "Featured Workspaces" we want to exercise some additional curatorial intent here. We may eventually add an 'email us' request to have your workspace featured. We're closing this for now to focus on other priorities
