### ISSUE TITLE
Ensure deployed version of Terra Job Manager uses the Terra logo as its favicon

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/terra-ui#1129]

**Comment by kleighwe** [comment]
@ruchim is this going to be handled by the Job Manager visual design?

**Comment by ruchim** [comment]
Yes! the initial styles that will be updated next week don't include the icon, as the goal is to make icons configurable, so the Terra JMUI can use its logo, and someone else's JM can use their own goal. But its the end goal for JM to be able to configure an icon.

**Comment by bradtaylor** [comment]
This went out :)
