### ISSUE TITLE
Possible bug with not saving profile to thruloe from Terra

### ISSUE THREAD

**Issue by breilly2** [DataBiosphere/terra-ui#1135]
Some users have managed to be in fully registered state but without a profile.

bt3.testing@gmail.com
nhjhk@channing.harvard.edu
phfrg@channing.harvard.edu

This causes problems with the free credit spreadsheet for Onix due to lack of information to populate the spreadsheet.

Could this be happening during registration? Is there some other path to reach this state?

**Comment by katevoss** [comment]
I think this issue came up recently but now that Terra doesn't have the whitelist, I think the problem is resolved. And there was a change made to Thurloe that should prevent this error in the future.
