### ISSUE TITLE
Notebook header pushed to the side 

### ISSUE THREAD

**Issue by elizzhao** [DataBiosphere/terra-ui#1136]
![Screen Shot 2019-01-29 at 1.30.36 PM.png](https://images.zenhubusercontent.com/5b7316806a9450578ab01159/a1240949-c13a-4df9-8bb1-b41580f066e3)

Notebook header is pushed to the side of the iframe. I think it might have to do with the python logo since it occurs after the python logo gets rendered (it initially starts in the middle, and is then pushed to the side). 

As of writing this ticket (1:30pm January 29th 2019), it only is on dev.

**Comment by katevoss** [comment]
This is now on prod:
![screen shot 2019-01-31 at 12 21 55 pm](https://user-images.githubusercontent.com/2395211/52072352-d144be00-2552-11e9-9ac0-90657891c905.png)
I think we should bump this in priority and put it in Ready for Eng, if not to the top of the list. @panentheos thoughts?

**Comment by elizzhao** [comment]
As per slack conversation: this is caused by the Leo Table of Contents extension which is installed by default. It appears to be on the Leo side to change those settings.

**Comment by zarsky-broad** [comment]
@bradtaylor is this still valid?

**Comment by katevoss** [comment]
I still see it, but sounds like it's a noop for us as the fix is dependent on the Leo team.
![Screen Shot 2019-04-18 at 2 07 32 PM](https://user-images.githubusercontent.com/2395211/56381644-7a5e9480-61e3-11e9-84f0-f3c0422176e8.png)

**Comment by breilly2** [comment]
Is there a leo issue that we can link to?

**Comment by katevoss** [comment]
Good call, there wasn't a ticket but now there is! https://broadworkbench.atlassian.net/browse/IA-962
