### ISSUE TITLE
Ensure zendesk guide support center lives at support.terra.bio

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/terra-ui#1141]
The comms team is publishing the Terra documentation and support site, built on Zendesk guide. This site has a default URL provided by zendesk: https://broadinstitute.zendesk.com/hc/en-us

However, it should be accessible from support.terra.bio.

We therefore need to configure the domain so that support.terra.bio displays the zendesk guide support site. @hjfbynara please advise on how to proceed from a devops perspective.

THIS SHOULD NOT BLOCK LINKING TO THE SUPPORT SITE
We can clean up URLs later

**Comment by tmm211** [comment]
I will provide the URL tomorrow and ask that it doesn't go live until Wednesday, Feb 6th.

**Comment by elizzhao** [comment]
blocked on devops terra.bio work

**Comment by elizzhao** [comment]
Zendesk lives at support.terra.bio! Links that reference `broadinstitute.zendesk.org` will automatically send to support.terra.bio, too.
