### ISSUE TITLE
Notification hidden when Notebook Runtime is open/expanded 

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/terra-ui#1146]
If an error message or other notification shows up when Notebook Runtime is expanded, it is hidden behind the Runtime: 
![Screen Shot 2019-01-31 at 11.36.09 AM.png](https://images.zenhubusercontent.com/580fc01f95e42b6c5bab0c94/7b8c8700-f3a0-4d96-bcdb-ba2feeba3eca)

I am assuming that the notification should appear on top of everything else on the page.

**Comment by zarsky-broad** [comment]
Related to #1098

**Comment by zarsky-broad** [comment]
This is in a modal now.
