### ISSUE TITLE
Too many requests when clicking Files in workspace area

### ISSUE THREAD

**Issue by adkinsrs** [DataBiosphere/terra-ui#1154]
When I am in my workspace area in the Data tab, and click the "Files" icon on the side, the page throws the attached error.  Since the error seems to be related to the maximum number of service accounts for the project, I assume others associated with this project ID will see this issue too if they replicate the steps.
<img width="1360" alt="screen shot 2019-02-05 at 11 47 02 am" src="https://user-images.githubusercontent.com/5665914/52289723-9bca1700-293c-11e9-9357-149a3e321aea.png">

**Comment by kleighwe** [comment]
This seems like a Cloud Accounts thing, we will forward to that team.
