### ISSUE TITLE
Remove references to FireCloud from Terra.

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/terra-ui#1165]
We are trying to teach users that ["it’s best to now think of “FireCloud” as synonymous with the NCI-sponsored project page that features TCGA and TARGET data"](https://software.broadinstitute.org/firecloud/blog?id=23430). We therefore wish to remove any written references to FireCloud in Terra.

These references occur in the following places:
[Dataset library](https://app.terra.bio/#library/datasets).  Rename "FireCloud Dataset Library" to "Broad Data Workspaces"

[Code&Tools library](https://app.terra.bio/#library/code). Rename "FireCloud Methods Repository" to "Broad Methods Repository"

Workspace tool cards. Rename "Source: FireCloud" to "Source: Methods Repository"

Scan the code for other instances where the name "FireCloud" is presented to the user. If additional locations are found, suggest an appropriate renaming that omits the word "FireCloud".

**Comment by bradtaylor** [comment]
Some discussion ongoing about whether we want to make this change at this time.

**Comment by katevoss** [comment]
Fixed by #1347
