### ISSUE TITLE
Create a project

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/terra-ui#1183]
As a program manager, I want to create a project associated with a particular billing account, so that members of this project can create resources charged to the account.

I may associated multiple projects with a single account, for the purposes of giving different groups of users different spending permissions, budgets, etc.

To create a project, I need to supply a unique name (globally unique to terra). I need to select which billing account I wish this project to charge against. from among a list of multiple accounts

**Comment by katevoss** [comment]
Release notes:
A user who has access to a Google Billing Account can now create a Billing Project within Terra. Reminder that billing projects are the prefixes for workspaces, i.e. `My-Billing-Project/My-Workspace`.

**Comment by katevoss** [comment]
This will actually be fixed in #1328
