### ISSUE TITLE
Firefox: Clicking link to go to Bucket from Data Model pop-up gets Error

### ISSUE THREAD

**Issue by schaluva** [DataBiosphere/terra-ui#1199]
When using Firefox: When you click on a link in the Data Model, you get a pop-up that has a link to the Google Bucket but clicking on the Google Bucket link adds it to the URL and you see an error instead of redirecting to the bucket. 
![image](https://user-images.githubusercontent.com/43828038/52803297-c8261780-304f-11e9-8f01-7761ecbfe7d6.png)

**Comment by zarsky-broad** [comment]
Fixed by #1430
