### ISSUE TITLE
Show an error or message when user is disconnected from the internet

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/terra-ui#1204]
When I lost internet connection, I started seeing Leo errors: 
![Screen Shot 2019-02-19 at 10.26.11 AM.png](https://images.zenhubusercontent.com/580fc01f95e42b6c5bab0c94/84e73c07-1267-4978-b37b-d3c5be663eee)

The actual problem was that I was no longer connected to the internet. We should let users know when they are disconnected so that it's clear they need to reconnect.

**Comment by zarsky-broad** [comment]
We could use [`navigator.onLine`](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine)

**Comment by breilly2** [comment]
Closing as duplicate of #1203 for now. Can follow up further if that doesn't cover all errors that pop up when disconnected.
