### ISSUE TITLE
Notebooks not listed in JupyterLab File Browser if not synced

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/terra-ui#1206]
I have 8 notebooks in my workspace.
When I open JupyterLab, only see 2 of them.

I need to go back to the Notebooks tab in my Workspace to see the full list and then take some action to force the localization of my notebooks.

## Option 1 - Open in JupyterLab
I clicked on the snowman on a notebook and selected "Open in JupyterLab".
The result is that it synced the notebook to the VM, and opened JupyterLab, but then I get a message:

Please use a different workspace.
This workspace is already in use in another JupyterLab window. Please enter another workspace name.

I could then close this Chrome tab and see that in my existing JupyterLab window, the notebook now shows up.

## Option 2 - Open in Jupyter
I double-clicked on a notebook.
The result is that it synced the notebook to the VM, and opened Jupyter.

I could then close this Chrome tab and see that in my existing JupyterLab window, the notebook now shows up.

**Comment by sharmatime** [comment]
Matt what were the circumstances that led to you having 8 notebooks in the workspace , but only 2 localized? Where these new notebooks you uploaded to the workspace or transferred from another workspace after you initially opened JupyterLab?

**Comment by bradtaylor** [comment]
We've removed JupyterLab until such time as we're able to provide a better syncing experience. I'm closing this as "wont fix" for now
