### ISSUE TITLE
Ignore Error Clusters in Terra UI

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1213]
AC: 
- User cannot see cluster in error status via Terra UI. 
- We treat cluster as if it was not there

**Comment by dglazer** [comment]
Hmm -- I've been confused by clusters in error status, but I'm not sure I understand the suggestions listed above. As a user, the two things I care most about (neither of which are clear in the current UI) are that:
a) it's clear I'm not paying for something I can't use, and
b) it's clear how to get a working cluster

If the proposal is to treat ERROR the same as NONE, so the UI shows I don't have a cluster at all, and gives me the usual play button to start one, that would work. (Separately, I assume we're keeping logs of cluster errors so developers can see how often they happen and make them more robust, But that doesn't need to affect the UI.)

**Comment by elizzhao** [comment]
After some discussion, we decided on a different implementation: 
* surface errored cluster and give user the chance to delete it
* filter out errored and deleting clusters from total cost estimate 
* users can spin up a new cluster by 1) pressing play or the cog from the errored cluster 2) deleting the errored cluster going to a no cluster state, and then spinning up a cluster from there

**Comment by elizzhao** [comment]
In addition to the above criteria, the updated implementation for dealing with errored clusters also automatically spins up the preset cluster if a user tries to open a notebook with an errored cluster.
