### ISSUE TITLE
Terra Crashes when Workflow with Redacted Snapshot Present

### ISSUE THREAD

**Issue by schaluva** [DataBiosphere/terra-ui#1230]
A user posted that when they try to open a workspace in Terra that contains a redacted snapshot, the entire website/app crashes entirely with an error message they were unable to capture by screenshot since it was crashing. They did manage to get the below screenshot of what they see before the crash. I tried to find a workspace with a redacted snapshot already present but couldn't locate one and I tried to test by importing a redacted snapshot but since that isn't possible, I am not positive this is a bug or not but this is what the user seemed to notice about this workspace as anomalous. 
![image](https://user-images.githubusercontent.com/43828038/53502867-e7279f00-3a7c-11e9-90ba-68e0e234b365.png)

**Comment by katevoss** [comment]
@breilly2 do you think this is related to https://github.com/DataBiosphere/saturn-ui/issues/1212?

**Comment by breilly2** [comment]
Somewhat similar concept but probably different. Snapshots (and their ability to be redacted) is on methods whereas #1212 is about method _configurations_. Both can be thought of as versioning of the artifact. These two issues are related to two different artifacts.

**Comment by bradtaylor** [comment]
Seeing something redacted should not break the app. Can we reproduce this?

**Comment by schaluva** [comment]
I can try and make some snapshots, import to a workspace, redact, and see if this happens.

**Comment by elizzhao** [comment]
Users now will see a warning with a tooltip explanation on redacted methods from the tools page. They won't be able to click into this redacted method. 

If a user were to navigate to the tool via a direct link, they will receive a message notifying them that the method has been redacted with an OK button to navigate back to the tools list.
