### ISSUE TITLE
Sharing Workspaces UI Inconsistency

### ISSUE THREAD

**Issue by schaluva** [DataBiosphere/terra-ui#1235]
When sharing a workspace, there is some instability when 1. typing a username and hitting enter + Save versus 2. typing a username, selecting option from the drop-down + Save. Option 1. sometimes results in failure to share workspace but not always. 
![image](https://user-images.githubusercontent.com/43828038/53577294-654e7900-3b43-11e9-8893-6d3dd629dc52.png)

**Comment by bradtaylor** [comment]
Isaac has thought through UX and will comment on this ticket. If he hasn't, go find that boi

**Comment by zarsky-broad** [comment]
Design should be similar to add user modal from groups/billing, on top of the list in this modal.

Autocomplete field with a role dropdown or checkbox next to it, and an add button next to that.

**Comment by elizzhao** [comment]
There is now a little form to add a collaborator at the top of the sharing workspace modal. 

To add a collaborator, fill out the required information (email, role) and click "Add user". The collaborator will be added to the list. Then **click Save** at the bottom of the modal to save the list of collaborators. 

Clicking and pressing enter on the username should also now both work to fill out the email field.

**Comment by elizzhao** [comment]
Not sure if actually noteworthy, but does change the experience around adding collaborators a bit. Up to comms discretion on whether or not to include in notes.
