### ISSUE TITLE
Workspaces Added/Shared E-mail Notifications

### ISSUE THREAD

**Issue by schaluva** [DataBiosphere/terra-ui#1237]
User is getting email notifications whenever their account is added to or removed from a workspace share list but  all "account notifications" are un-checked in their profile. 
![image](https://user-images.githubusercontent.com/43828038/53591153-5c6ca000-3b61-11e9-845b-4ca30362cf14.png)

**Comment by katevoss** [comment]
Thanks for reporting this, it is indeed a bug in the UI. I tested by going to the FireCloud UI and comparing the account notifications with Terra, and when all of the Account Notifications checkboxes are selected in FireCloud, none are selected in Terra. Moving to Ready for Eng.
