### ISSUE TITLE
Session history can get too large and fails to load

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/terra-ui#1259]
Reported by @tmm211:

Tiffany could not load any workspaces because her browser session had exceeded the size. This could be an issue for other users who have access to many (many) workspaces.

Her console error is here:
![screen_shot_2019-03-07_at_12.36.17_pm.png](https://images.zenhubusercontent.com/580fc01f95e42b6c5bab0c94/41821173-28bf-4cbf-ab83-6494810f7a97)

@bradtaylor for FYI

**Comment by bradtaylor** [comment]
FireCloud paginates it's workspace list. Would doing that fix this? Other users have reported slower performance
