### ISSUE TITLE
Improve handling of privacy tools such as Privacy Badger, Ghostery, etc

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/terra-ui#1273]
Support has fielded a number of issues where users of Privacy Badger are unable to log in. It causes a failure in a call to SAM.

Many people use privacy badger with Google cloud and other websites. Why does it break ours? Can we fix it?

If not, can we at least detect when we suspect a privacy tool is running and display a friendly alert message asking users to whitelist Terra or disable their privacy tool when using Terra?

**Comment by breilly2** [comment]
Privacy Badger is working as designed.

We can add a failure handler on auth and prompt the user to check whether they are using a privacy blocker such as Privacy Badger.

**Comment by bradtaylor** [comment]
@zarsky-broad @breilly2 Can you please comment here with the results of the spike? Specifically:
* Why Privacy Badger breaks Terra's google SSO call
* Speculation as to why it may not break other apps that use google SSO, and why we cannot set ours up similarly

**Comment by bradtaylor** [comment]
Given that it appears we cannot alter our SSO approach to avoid being broken by privacy badger, we should:

* Detect failures
* Ask the user if they are using Privacy Badger or a similar privacy product
* Explain to the user that this isn't due to cookies (most user's expectation)
* Tell the user what to do in order to make Privacy Badger (or similar products) work with Terra.

I am Removing the "Spike" label and bringing this ticket back to Ready for Eng

**Comment by bradtaylor** [comment]
@jaredbancroft mentioned that ghostery has the same issue. I'm generifying this issue to 'privacy tools'. @elizzhao please be aware and let me know if this is more complicated than I think. Thanks!

**Comment by elizzhao** [comment]
Due to some limitations around what we can actually catch and handle since the actual call that fails happens outside our system, the solution we came up with:
- user fails to sign in 
- toast notification appears that the sign-in failed 
- clicking on this notification opens a modal that says the failure could be due to privacy tools. The user should disable them, refresh, and try again. 

See connected PR for details
