### ISSUE TITLE
Unify canonical ToS and Privacy

### ISSUE THREAD

**Issue by zarsky-broad** [DataBiosphere/terra-ui#1287]
Currently we show the ToS in a modal from our code, but link to the support site from the footer. As of this writing, the version in our code is newer.

We have the privacy policy in a page. It's not on the support site anywhere.

Where should it be? Let's put it there. If it's on our site, we should make sure people can see the privacy policy when they haven't yet signed the ToS but have signed in.

@bradtaylor this is ultimately probably your call.

**Comment by kleighwe** [comment]
No longer a problem, we have an alternative fix.
