### ISSUE TITLE
Update deploy time due to DLS

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/terra-ui#1289]
Due to the daylight savings switch, our daily deploy to prod now happens at 11am EST. Let's switch back to 10am.

@zarsky-broad I believe you made the change in the cron job last time, do you mind recording this change in the Wiki?

**Comment by breilly2** [comment]
The fix is to update the cron scheduling in the config in the saturn-ui-prod-deploy repo.

**Comment by breilly2** [comment]
Updated cron schedule used by circle. We'll need to manually do this twice a year. I added a slack reminder for Nov. 1 in the #saturn and #terryls-announcements channels.
