### ISSUE TITLE
Console error when using AutocompleteSearch

### ISSUE THREAD

**Issue by elizzhao** [DataBiosphere/terra-ui#1310]
![Screen Shot 2019-03-20 at 10.10.43 AM.png](https://images.zenhubusercontent.com/5b7316806a9450578ab01159/ffb8cbbe-a3c0-4dc7-9110-a451325235eb)

Error appears when using autocomplete search and clicking on a selection. We use this component when adding users to groups or billing projects right now. 

AC: fix the console error

**Comment by katevoss** [comment]
I can take a look into this as a part of working on #1188. I will update here if I am able to fix it.
