### ISSUE TITLE
Closing out of Tool config after Save doesn't save changes to Data Selection

### ISSUE THREAD

**Issue by schaluva** [DataBiosphere/terra-ui#1311]
When user goes to Tool and makes a Data Selection and hits Save then exits the Tool to navigate away to another tab (for some reason X) and returns back to the Tool they had just configured with a set of Data, their original selection is not saved. Instead, the selection is switched back to the original "Process all". If they do not notice this (since they hit Save already), they might Launch Analysis on all samples even if that is not the intended set.
Screenshots below:
1. Chose 2 samples from the Data Selection step, changed an Input.

![Screen Shot 2019-03-20 at 2 12 22 PM](https://user-images.githubusercontent.com/43828038/54708848-a1f60a80-4b1a-11e9-9924-87b05dbda2af.png)

2. Hit Save and Launch Analysis button activates.
![Screen Shot 2019-03-20 at 2 12 34 PM](https://user-images.githubusercontent.com/43828038/54708847-a1f60a80-4b1a-11e9-96e6-9cd159d8e14d.png)

3. Realized I needed to look at my Data Model so swapped to that tab. 
![Screen Shot 2019-03-20 at 2 12 46 PM](https://user-images.githubusercontent.com/43828038/54708846-a1f60a80-4b1a-11e9-873a-e1d2df6b9047.png)

4. Finished checking my Data Model and go back to Tools but now my selection is reset to all 3500 samples. Didn't notice this since i had already hit Save and I Launch Analysis on 3500 instead of 2 samples. oops.
![Screen Shot 2019-03-20 at 2 12 59 PM](https://user-images.githubusercontent.com/43828038/54708845-a15d7400-4b1a-11e9-8e6d-76d3edd8b890.png)

**Comment by schaluva** [comment]
From report file from ZD ticket [#1363](https://broadinstitute.zendesk.com/agent/tickets/1363)

**Comment by tmm211** [comment]
+ A million
This happened at the hackathon!
