### ISSUE TITLE
Popular ad-blocking and privacy tools break Terra

### ISSUE THREAD

**Issue by jaredbancroft** [DataBiosphere/terra-ui#1320]
Behavior:
Clicking the upper left hamburger menu produces the following results.
![Screen Shot 2019-03-20 at 9 22 29 PM](https://user-images.githubusercontent.com/22916639/54778094-2fecf680-4bea-11e9-8356-3e97fc7e818b.png)

To reproduce:
Chrome Version 72.0.3626.121
Ghostery for Chrome version 8.3.1 - Global Blocking All
Click the hamburger menu

Workaround:
Pausing ghostery or trusting site allows the hamburger menu to function properly

**Comment by bradtaylor** [comment]
Hi @jaredbancroft, the team is working this as issue #1273. That issue specifically mentions privacy badger, but the solution should be generic to other privacy tools (error looks the same). I'll update the other issue to mention ghostery.

I'm going to close this issue as a duplicate. Thanks very much for reporting this!
