### ISSUE TITLE
Data entity information not available in Job History

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/terra-ui#1322]
In FireCloud, there was a way to see what entity a job was run on:
<img width="1286" alt="Screen Shot 2019-03-22 at 10 12 28 AM" src="https://user-images.githubusercontent.com/14941133/54828685-1a7bd900-4c8b-11e9-8fe8-44b2f8c0b055.png">

However, that information is missing from the Terra UI -- which makes tracking jobs a lot harder.
<img width="1022" alt="Screen Shot 2019-03-22 at 10 12 41 AM" src="https://user-images.githubusercontent.com/14941133/54828729-2ebfd600-4c8b-11e9-9672-77f0059ed947.png">

AC: I'd like visibility into what entities my various submissions relate to, as a way of understanding what jobs relate to which components of my data model.

**Comment by zarsky-broad** [comment]
Fixed by #1398
