### ISSUE TITLE
Spike: Back End work with Onix for Billing

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1326]
Related to #1192, this ticket represents the back end work that is necessary to record the CO data, and establishes where we store it.

**Comment by breilly2** [comment]
Draft of information/summary/decisions to date: https://docs.google.com/document/d/1GpKa2DwHB3noPym5-AfBAOCiFXpk5J3mgKWpqy3bcIo

**Comment by breilly2** [comment]
Moved the write-up to https://docs.google.com/document/d/1MVagpXQMLtR15fKzom11nw3lR-i4NWImk5H2iERK-t0 which is a shared document between us and Onix. Conversations will be ongoing. This concludes the spike of initial planning with Onix.
