### ISSUE TITLE
Change tool snapshot version

### ISSUE THREAD

**Issue by zarsky-broad** [DataBiosphere/terra-ui#1329]
A user should be able to change the version of a method pointed to by a config in the 'tools' tab.

This is our top support forum feature request.
https://broadinstitute.zendesk.com/hc/en-us/community/posts/360042788112-Updating-Tool-Snapshot

AC: 
- When editing a Method/Tool config, we should be able to change the method/tool version via a dropdown and save to the backend. 
- An update in place. 

Dependencies?

**Comment by elizzhao** [comment]
Snapshot can now be changed by a dropdown on the workflow view.
