### ISSUE TITLE
Reduce NPS sample frequency

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/terra-ui#1333]
first ask 7 days after registration
re-ask 90 days after answer/dismiss

**Comment by breilly2** [comment]
@bradtaylor Thinking more, there are some edge conditions that might be worth thinking about. One in particular is someone who first signed in during the 7 days leading up to deploying this change and then came back, was presented with the NPS widget, and responded or dismissed it. For them, we will not prompt them again for somewhere around 83 days. In other words, we will skip sampling them at the newly desired 7 day mark.

I don't know how feasible it is to try to address this, but I wanted to make sure you were aware of it so you could decide whether that is okay or if we should attempt to do something about it.

**Comment by elizzhao** [comment]
Changed the sample frequency for nps as the ticket intended. Closing for now. (Can re-open should we want to try and do something about the corner case)
