### ISSUE TITLE
support alternate logos by domain

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/terra-ui#1338]
Display a logo configured by a domain. First is a white-version of the Firecloud logo (to be provided by Lou) displayed at firecloud.terra.bio

Logo should have roughly the same dimensions as current logo

**Comment by kleighwe** [comment]
@lstrano-broad are we ok to put this "in design"?

**Comment by lstrano-broad** [comment]
Will do

**Comment by lstrano-broad** [comment]
White and full color
[FC logo and icon.zip](https://github.com/DataBiosphere/terra-ui/files/3035406/FC.logo.and.icon.zip)
 version of FC logo and icon attached...

**Comment by lstrano-broad** [comment]
![FCpoweredbyTerra-white.svg](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/0b8cdd73-8b07-488f-912a-43f241bcbe82)

Need to state "Powered by Terra" with FC logo. New logo attached.
