### ISSUE TITLE
Bug when on a slow network that breaks the app

### ISSUE THREAD

**Issue by elizzhao** [DataBiosphere/terra-ui#1344]
![Screen Shot 2019-03-27 at 10.45.19 AM.png](https://images.zenhubusercontent.com/5b7316806a9450578ab01159/95c32357-1fc5-4671-9a77-131259ad6cd9)

Bug that mohs found! 
Reproduce: 
When on a slow network connection (Slow 3G), open Terra LP, and before the page fully loads, open sidebar, try to navigate to workspaces, this happens. 

On first glance, Brett thinks index.js is where to start looking

**Comment by panentheos** [comment]
I believe this has been fixed. If we see this again, please reopen.
