### ISSUE TITLE
Deprecating FC UI Tests

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1348]
As part of the redirect, we're eliminating many of the FC UI tests. We should work with QA to ensure we maintain proper test coverage in Terra. 

AC: 
- There's a test plan and tickets are generated for any further actions.

**Comment by bradtaylor** [comment]
Ambica has the lead on creating a test plan. She a team dedicated to triaging these tests and fixing them. We should assign a Terra point of contact to answer questions here, but I am not planning on dedicating significant development capacity to this effort. I'm closing this as a "invalid" as I don't think it's truly meant for this team's board.
