### ISSUE TITLE
Decrease frequency of Workspace API Calls

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1349]
@panentheos talk to @bradtaylor 
We're currently refreshing the workspace whenever someone navs around their workspace tabs. FC cashes. We should cache
THIS SHOULD NOT BE A SLOW CALL
email the performance working group noting our concern about what happens when many more users show up to make this call. This API should be improved. This is a UI bandaid (that we should apply!)

**Comment by bradtaylor** [comment]
Questionable if this needs to be done for May1
