### ISSUE TITLE
Design & Implement a toast redirect message

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1350]
"Create an interstitial page to be shown the first time a user is redirected to smooth out the experience for both firecloud app redirect and forums."

Engineering: 
- We can detect the first time that a user visits firecloud.terra.bio and show them a welcome message/page. Likely using local storage. 

Dependencies:
- Visual Design
- Product decision on how this will work. 

Open Questions:
- Can we use Rex response to help with this?

**Comment by bradtaylor** [comment]
What if this was on the firecloud.org pages so whenever a user went directly there, we reminded them what was happening. Then we wouldn't have to store state. We rely on the user's behavior of going to the other place vs the new place. Thoughts?

**Comment by bradtaylor** [comment]
Talking with the team, we want this to be a toast notification, so it's not as annoying as an interstitial, that links out to some nice documentation. We want this to be connected to the redirect query parameter, so users see it when they've been redirected.

Brad will talk with Robert M to get text

**Comment by bradtaylor** [comment]
We should also strip off the query parameter after we get it.

**Comment by bradtaylor** [comment]
The notification should time out after 30 seconds

**Comment by davidangb** [comment]
the query parameter in question is `fcredir=1`, e.g. `https://bvdp-saturn-dev.appspot.com/?fcredir=1#workspaces`

**Comment by elizzhao** [comment]
Coming out of the soft redirect new AC:

Redirected users see a notification welcoming them to the new UI. This notification should tell users that they can optionally revert to the classic FireCloud UI, via a link in the left-hand nav.

AC:

The notification should indicate that the legacy version will be available until “August 2019” with a link to the blog post that will explain more
This notification should allow the user to navigate the Terra site while it is displayed
It should persist until the user dismisses it.

**Comment by katevoss** [comment]
@bradtaylor thoughts on wording and other suggestions? 
![Screen Shot 2019-04-17 at 9 51 21 AM](https://user-images.githubusercontent.com/2395211/56293103-79036e00-60f6-11e9-9abf-c5d3d15d1a33.png)
