### ISSUE TITLE
Make a Terra TOS Page

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1352]
> P2 We have a standalone “Terra Terms of Service” page that we can link to and is regularly updated.

OPTION: Make this page "out-of-app" so that any team can update it in the future. (Means TOS could be updated RE a script)

Needs Product: 
- Where does this go (in app or not)? 
- Who needs to have the power to change it (will we become a bottleneck for this in the future?) 

AC:
- Make a TOS page.

**Comment by bradtaylor** [comment]
We already present TOS in app. There is already a static TOS page in the support center that we persistently link to from the app. https://broadinstitute.zendesk.com/hc/en-us/articles/360024688731-Terms-of-Service

Keeping those in sync might be challenging, but is it worth additional engineering effort?

The TOS change process should involve review from both Broad and Verily legal stakeholders. That process is in progress. I think we can expect updates to be no more frequent than over the past Q, and likely less. My feeling is that this can be pretty manual, in which case this is a no-opp. Anyone care to disagree?

**Comment by bradtaylor** [comment]
The team feels it is imperative that we have a page hosted by the app, that automatically picks up updates as they are made.

**Comment by elizzhao** [comment]
TOS page now exists in the app and can be found by clicking "Terms of Service" in the footer.
