### ISSUE TITLE
Placeholder: Apply 'under construction' Banner to any FireCloud UI page we direct users to

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1354]
Banner text: (to be provided by brad)
Banner should redisplay on every refresh of the page.
Banner should be displayed when we release the redirect (not before)
Banner should include the terra logo and background (similar to current 'terra is coming' banner)

**Comment by kleighwe** [comment]
@bradtaylor we need to decide when to release this

**Comment by elizzhao** [comment]
PR on the firecloud ui has been merged! The "under construction" text won't appear until the redirect goes out and is conditional on the "return=terra" in the url. 
Banner text ended up being: This page is displaying in our legacy application. Please bear with us as we migrate these features fully into Terra.
