### ISSUE TITLE
Change the NPS aggregation conditions in Looker

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/terra-ui#1358]
Currently Looker reports a monthly NPS as well as a 90-day trailing average, where multiple responses submitted by the same user are counted individually. The second of these is a relatively non-standard way of measuring aggregate NPS and is not meeting our needs.

Instead, we should report all-time NPS to date. So for the month of January, we report two numbers: the NPS for responses in January (same as now), as well as the all time responses up through January 31st.

When aggregating the second number, we will have duplicate responses from the same individual. We want to remove all but the _most recent_ response from an individual in the all-time numbers.

*If it is more than 1 day of work to report all-time-to-January31 with duplicate removal:*
Just take the aggregate rolling aggregate out of the monthly chart altogether. Report all-time-date-with-duplicate-removal as a single number in another panel.

**Comment by breilly2** [comment]
To clarify, you want the all-time-to-_some-date_-with-duplicate-removal either way... One option is to report that number per month in the graph... The other option is to report only the number as it is right now without any historical data... The difference being that the number reported for January would include a response from someone even if they also responded in February, and then the number reported for February would include that new response and filter out the January response?

**Comment by bradtaylor** [comment]
@breilly2 Correct. My guess is that the 'without any historical data' is way way easier. We can and should do that first if so

**Comment by breilly2** [comment]
@bradtaylor, I implemented an Overall NPS calculation. I don't love that there isn't much visibility into the calculation of this number, but at least it's there. It wasn't immediately obvious to me how to calculate this by month so I didn't do that for now. If this is sufficient for now, maybe we can call this issue done and make a new issue for the improvement sometime in the future?

**Comment by breilly2** [comment]
I did verify the calculation manually based on the current data. FWIW, I found there were 2 cases of multiple responses from non-internal users. In both cases, the score in the response was in fact lower... one 5 down to 1 (consistent detractor) and one 10 down to 8 (promotor to passive).

**Comment by katevoss** [comment]
@breilly2 how can I test this out?

**Comment by breilly2** [comment]
You could check out the dashboard in Looker. At this point, it's probably mostly on @bradtaylor's plate to look at the dashboard and make sure it's what he was looking for.

**Comment by breilly2** [comment]
Reviewed with Brad in person.
