### ISSUE TITLE
Temporarily take out the global jobs list view

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/terra-ui#1361]
While in theory, the "Jobs" global view in Terra has the powerful ability to review jobs across the workspace boundary...

The concerns with that view today are:
1. The columns in Job manager today make it hard to filter on criteria like workspace name, submitter, method name, etc....
2. There are performance [issues](https://github.com/DataBiosphere/job-manager/issues/613) in scenarios where a user has access to hundreds of thousands of workflows (though rare) 

Suggestion: Let's get usable filter criteria such as workspace name, submitter, method name added to the job manager view, and only then expose a link in the Terra UI that shows people a list of their most recent jobs across various projects.

**Comment by ruchim** [comment]
Another +1 from David B and Lee on this -- as this view is not useful until theres a way to filter by Submitter.

**Comment by elizzhao** [comment]
Resolved via #1639
