### ISSUE TITLE
Default Outputs not working with Dockstore Imported Tool

### ISSUE THREAD

**Issue by schaluva** [DataBiosphere/terra-ui#1362]
What works: Export of Tool from Dockstore to Terra workspace. Upload .json for Tool inputs. 
What doesn't work: When you press "Use Defaults" in Outputs (of a Tool), it does not auto-fill Attribute column values automatically.

Found a workaround: 
Click on an Output Attribute empty box and choose ANY output that shows up from Data Model.
<img width="1017" alt="Screen Shot 2019-03-28 at 4 28 12 PM" src="https://user-images.githubusercontent.com/43828038/55190736-d0a55e00-5176-11e9-801f-7e0c8aa1c71d.png">

Delete the filled-in attribute.
<img width="992" alt="Screen Shot 2019-03-28 at 4 28 50 PM" src="https://user-images.githubusercontent.com/43828038/55190869-1a8e4400-5177-11e9-8b2c-72995d47841f.png">

Then press "Use Defaults" and the Attribute fills in automatically.
<img width="865" alt="Screen Shot 2019-03-28 at 4 28 59 PM" src="https://user-images.githubusercontent.com/43828038/55190821-00ecfc80-5177-11e9-822e-599dd292d47a.png">

Only works for each attribute blank you go into, choose a random output, click "x", then press "Use Defaults".

**Comment by breilly2** [comment]
Can you share the workspace with us? Maybe use the general support group (I should make a managed group that includes all of Team Saturn).

**Comment by schaluva** [comment]
@breilly2 I shared it with the FC Support group but a saturn specific one would be great!

**Comment by breilly2** [comment]
@schaluva What is the workspace name?

**Comment by schaluva** [comment]
oops https://app.terra.bio/#workspaces/help-gatk/hca_optimus_testing
