### ISSUE TITLE
in-app message for correct .tsv entity:table_name_id convention

### ISSUE THREAD

**Issue by schaluva** [DataBiosphere/terra-ui#1366]
When a user uploads a .tsv file to populate their Data Model - 
1. more details need to be given in the app to show that they are missing the "_id"
2. explanation around the freedom of table names they can use - no longer have to use the samples/participants/pairs convention as in FC

**known caveat: custom entities cannot have references between tables

(will pass along all above information to knowledge base team to add to documentation)

**Comment by katevoss** [comment]
This is the current state of the modal, is this clearer?
<img width="639" alt="Screen Shot 2019-05-14 at 10 09 09 AM" src="https://user-images.githubusercontent.com/2395211/57704659-59496200-7630-11e9-8e26-44b3ceb0242d.png">

**Comment by kleighwe** [comment]
@schaluva is this still a problem?

**Comment by schaluva** [comment]
Nope I think we are all set!

**Comment by panentheos** [comment]
This is resolved, closing.
