### ISSUE TITLE
what workspace am I in?

### ISSUE THREAD

**Issue by dvoet** [DataBiosphere/terra-ui#1369]
When I select a workspace in the Terra UI the bread crumb at the top says my workspace nice and big:

![image](https://user-images.githubusercontent.com/1521333/55282976-2ec47380-5326-11e9-9663-2995453311ca.png)

But when I choose a tab it gets small and it is the only place that says what workspace I am in. And the part that is big is the tab I am on which is already emphasized:

![image](https://user-images.githubusercontent.com/1521333/55282982-587d9a80-5326-11e9-9996-f8d75aa5abe8.png)

I think the workspace name should remain easy to see and having the tab name in the breadcrumb does not add value.

**Comment by kleighwe** [comment]
Problem should be solved within @jeromechadel 's redesigns.
