### ISSUE TITLE
Include Public Workspaces in Terra 

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1374]
Sometimes people make their workspace public, but don't catalog it in the library. 

We want to make a check box for "show public workspaces" in the Workspaces list. 

AC:
- A checkbox exists (unchecked by default) which toggles public workspaces on and off from a user's Workspace list.

**Comment by elizzhao** [comment]
Checkbox added that toggles whether or not public workspaces are included in the workspace list.
