### ISSUE TITLE
FCUI Return Paths

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1378]
To be filled in by @bradtaylor 
What subdomain did you come from when going to the old FCUI- app.terra.bio or firecloud.terra.bio, so that when we send you BACK into terra, having found juicy content, you end up in the right place

**Comment by bradtaylor** [comment]
We already include a return value! https://portal.firecloud.org/?return=terra#methods
So if in terra, we're linking you from firecloud.terra.bio we should set that to return=FireCloud
in FireCloud we should respect that

**Comment by elizzhao** [comment]
Closing because all connected PR's are closed and merged in
