### ISSUE TITLE
Change FC login page to make it Terra-y

### ISSUE THREAD

**Issue by elizzhao** [DataBiosphere/terra-ui#1388]
When clicking on the Broad Data repo or Broad methods repo links, the user gets directed to Firecloud. Then, the user may be prompted to login to Firecloud. The login page still has the Firecloud logo and Firecloud branding which need to change.

**Comment by bradtaylor** [comment]
Brad to provide new language.

**Comment by elizzhao** [comment]
Updated information from soft redirect requirements:

FCUI also always looks for the presence of “return=terra” (or "return=firecloud") in the URL querystring. If this is present users see a terra version of the FireCloud sign in screen with different text.

**Comment by elizzhao** [comment]
Corresponding PR in fc-ui was merged. Final language can be found there. 
Change: if a user sees the sign-in page on firecloud and came from one of the terra.bio domains, they see a custom sign-in page with updated language, instructions, and the Terra logo.
