### ISSUE TITLE
Add link to Comparison with FC to side nav for firecloud.terra.bio

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/terra-ui#1396]
When a user visits firecloud.terra.bio, in the left Side nav they should see a link to: https://broadinstitute.zendesk.com/hc/en-us/articles/360022694271-Side-by-side-comparison-with-Terra

Link text should be: (TBD from @bradtaylor )

**Comment by elizzhao** [comment]
Should we include this as part of the redirect? It's not the epic so it might get missed if so
