### ISSUE TITLE
UChicago Fence Account Linking

### ISSUE THREAD

**Issue by breilly2** [DataBiosphere/terra-ui#1397]
Related to #1372. Just like FireCloud does, this should go through Bond.

**Comment by breilly2** [comment]
This one _does_ require someone to authorize the redirect URL. FireCloud uses `https://portal.firecloud.org/#fence-callback`. We could use `https://app.terra.bio/#fence-callback` and `https://firecloud.terra.bio/#fence-callback`. Ideally they could allow any `terra.bio` subdomain, I guess. Attn: @bradtaylor

**Comment by kleighwe** [comment]
Update: Reached out to @abaumann on 4/18 about whether UChicago has gotten back to us or not. They haven't. Alex re-emailed Zach, and I'll be asking around to see if/how we should escalate.
