### ISSUE TITLE
Terra Workspace Card doesn't show Auth Domain

### ISSUE THREAD

**Issue by schaluva** [DataBiosphere/terra-ui#1403]
In FireCloud, if a workspace has an Authorization Domain, you can see it from the card so you know that you need extra permissions. In Terra, the workspace card doesn't show if it has Authorization Domain so you have to click into it and then you get a general error that says "Could Not Display Workspace" which could mean you don't have access for a few different reasons. 

![Screen Shot 2019-04-08 at 11 45 02 AM](https://user-images.githubusercontent.com/43828038/55737899-12929780-59f4-11e9-9943-541e105173bf.png)
![Screen Shot 2019-04-08 at 11 44 51 AM](https://user-images.githubusercontent.com/43828038/55737900-12929780-59f4-11e9-8bbf-17130a5a452c.png)

**Comment by katevoss** [comment]
@bradtaylor is this necessary for May 1?

**Comment by panentheos** [comment]
We now show an on-hover message for these workspaces which explains why you don't have access. There will be a separate ticket for requesting access.

**Comment by schaluva** [comment]
@panentheos Would you be able to add a Noteworthy tag to this so it can go into Release notes? I think users will like this feature :)
