### ISSUE TITLE
"Go back to Classic FireCloud" Option

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1422]
FireCloud.terra.bio should include an extra option in its left-hand nav: “Go back to classic FireCloud”. This link should take users to the legacy version of the FireCloud UI

AC: Link exists. See comments below for additional ACs

**Comment by kleighwe** [comment]
@bradtaylor: how persistent should the revert from this link be? Talk to @davidangb for specifics. (For the session, as long as I'm on this browser, etc).

**Comment by bradtaylor** [comment]
@davidangb I believe we worked through this in person. It's permanent- you are setting your default by clicking the link.

**Comment by bradtaylor** [comment]
We should ask users who opt-out what is their primary reason for doing so, with a free-text response. So, should pop up a modal asking users to confirm their sure that they want to use the classic URI by default. We should have a free-text field response. Where should this response go? Suggesting it gets sent to zendesk so CS can see it. Similar to contact us modal. We only want to send this if the user has provided actual feedback text. Include a checkbox if it's ok to follow up with the user by email, which can also be included in a ZD ticket.

**Comment by bradtaylor** [comment]
This should set the thurloe TerraOptOut preference key to a an epoch timestamp (so CS knows when user opted out)

**Comment by elizzhao** [comment]
Link and Modal to go back to classic firecloud was made and merged! Link is in the left-nav. It can send feedback to zendesk and hits the orch endpoint to set `preferTerra=false`
