### ISSUE TITLE
"Welcome to the new UI" Notification

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1423]
Redirected users see a notification welcoming them to the new UI. This notification should tell users that they can optionally revert to the classic FireCloud UI, via a link in the left-hand nav.

AC:
- The notification should indicate that the legacy version will be available until “August 2019” with a link to the blog post that will explain more
- This notification should allow the user to navigate the Terra site while it is displayed
- It should persist until the user dismisses it.

**Comment by kleighwe** [comment]
@elizzhao will add to existing issue

**Comment by elizzhao** [comment]
Added the new AC information onto the pre-existing ticket #1350. Closing as duplicate
