### ISSUE TITLE
Track "Opted-Out" Users

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1424]
We must collect the emails of users who choose to opt-out. These should be easy to aggregate and deliver to customer success for followup.

Dependent on answer to "Opt out" question (#1422)

**Comment by bradtaylor** [comment]
@davidangb If we are storing the opt-out decision in thurloue per #1422, and Thurloe values are in BigQuery, is there anything to actually do here?

**Comment by bradtaylor** [comment]
Brad will confirm with Alex that this is a no-op from the Terra perspective

**Comment by bradtaylor** [comment]
Confirmed it as a no-op. Closing this story as "invalid" because there turns out to be nothing to do
