### ISSUE TITLE
FCUI Looks for user's opt-out preference. 

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1426]
FCUI always looks for the user’s opt-out preference, which defaults to “TerraOptOut: 0”.
 - If FCUI sees that the user has a “TerraOptOut” value that is > 0, then:
 - - FCUI does not automatically redirect to Terra for any page
  - FCUI will display a notification banner with a link that allows the user to navigate over to Terra.
- - Banner should say something to the effect of “you’ve got until August 2019!” (@ brad what should the banner say?)  
- If FCUI sees that the user’s TerraOptOut == 0, then:
-- FCUI automatically redirects to Terra for most pages (methods repo and library do not redirect)

**Comment by kleighwe** [comment]
@bradtaylor can you give wordage here?

**Comment by bradtaylor** [comment]
wordage given on PR
