### ISSUE TITLE
"Opt back in to Terra" Banner

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1428]
Terra UI also looks at the user’s “TerraOptOut” value, defaulting it to 0. If Terra UI sees “TerraOptOut” > 0:
- Display some kind of banner/notification asking if the user wants to opt back in to Terra

 (@bradtaylor , what would you like this to say? Also, Is this for app.terra, firecloud.terra or both?)

**Comment by bradtaylor** [comment]
We've decided that we don't want to bother people if they're choosing to go to firecloud.terra.bio. We can always reopen if patterns of user behavior make us feel this is necessary. I'm going to close as a wont-fix for now
