### ISSUE TITLE
Swatomation Test coverage before all tests are transitioned. 

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1429]
Goal: until swatomation tests are fully transitioned, we remain reliant on FCUI tests to provide coverage. Provide a way for these tests to use the full legacy FCUI functionality.

Continue to hide all redirects behind a config setting in FCUI.  Ensure that FiaBs, alpha, and any other environment in which we run tests has the config setting set to false. This would force all tests to see the full legacy FCUI featureset, and not redirect to Terra.

**Comment by bradtaylor** [comment]
so should set a config flag to disable redirects in our qa firecloud environments (dev/alpha/perf/perf2/etc). Coordinate with QA on the full set of environments.

**Comment by zarsky-broad** [comment]
Currently verifying with QA.

**Comment by zarsky-broad** [comment]
For posterity: the conclusion reached was that redirects should be disabled in Alpha and on FiaBs.
