### ISSUE TITLE
Terra doesn't load in Firefox

### ISSUE THREAD

**Issue by tlangs** [DataBiosphere/terra-ui#1434]
Going to [The Terra homepage](https://app.terra.bio/) in Firefox 60.6.1esr gives a "Loading!" screen that never goes away.

**Comment by katevoss** [comment]
Unfortunately FireFox is not a supported browser for Terra, though I did just sign in successfully on FF. Did you try a hard refresh?

**Comment by tlangs** [comment]
A hard refresh did nothing for me.

**Comment by zarsky-broad** [comment]
Could this be connected to https://github.com/DataBiosphere/terra-ui/issues/1273?

**Comment by zarsky-broad** [comment]
@tlangs this should be fixed as of tomorrow, can you try again?

**Comment by panentheos** [comment]
I was seeing the same issue, and it now loads.
