### ISSUE TITLE
TSV import for workspace data

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/terra-ui#1440]
Currently we only allow workspace data values to be manually entered one at a time. Users expect the ability to upload them via TSV. This is an important FireCloud feature we should bring forward

**Comment by bradtaylor** [comment]
TSV only at the moment. Not supporting JSON, txt, etc.

**Comment by bradtaylor** [comment]
import attributes TSV is a POST endpoint on orchestration. Rawls does not have it, so do it through orch.

**Comment by seanhorgan** [comment]
Cross pointing this comment from #816:

Can we name this data upload something more descriptive than "Upload TSV"? AFAIK this requires a specific format so a general TSV won't work. E.g. "Upload workspace attributes".

Along these lines, can we standardize on the name of this type of data. In the UI it's referred to as "Workspace Data" while the TSV download refers to it as "-workspace attributes". My preference is "Workspace Attributes" as this term data is already overload in the workspace context.
