### ISSUE TITLE
Change URLs to follow standardized structure

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/terra-ui#1445]
In Terra URLs, we occasionally have query strings (?) after a fragment component (#). This happens in JupyterLabs and Billing. We should follow the proper URL standards and put the query string before the fragment component.

**Comment by zarsky-broad** [comment]
This is intentional, based on how our history library constructs URI's.

**Comment by katevoss** [comment]
@davidangb brought this up earlier this week, does this warrant a conversation?

**Comment by zarsky-broad** [comment]
I don't think so. We're aware of the ways in which we're non-standard, and we did them knowingly.
