### ISSUE TITLE
Selecting "Delete cluster" while notebook is opened does not delete  the cluster

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/terra-ui#1451]
When I have a notebook opened and I select "Delete cluster", the following occurs:

- Browser navigates to the Notebooks list

Nothing else seems to occur. I don't see any indication in the UI that the cluster is being deleted.
If I refresh the page the cluster panel continues to just show "Running". Now if I select "Delete cluster", the panel transitions to showing "NONE" for the notebook runtime.

**Comment by katevoss** [comment]
Related to #1384

**Comment by katevoss** [comment]
I'm closing this as a duplicate of #1384, which should be fixed soon. Thanks for the feedback!

**Comment by mbookman** [comment]
Tested this and the behavior is great. Thanks!
