### ISSUE TITLE
"Ghost Variables" when changing Snapshots fail to upload Attributes via inputs.json

### ISSUE THREAD

**Issue by schaluva** [DataBiosphere/terra-ui#1464]
When a Tool Snapshot is toggled, the UI shows the updated list of Variables in Inputs but uploading an inputs.json file errors.

Detailed Steps:
1. Export a Tool's Snapshot 1 to Workspace.
2. Inputs.json file successfully uploads and analysis runs with Snapshot 1.
3. Change Tool Snapshot 1 that removes variables from Inputs list to create Snapshot 2.
4. Export Snapshot 2 and upload Inputs.json file specific to Snapshot 2 from Terra.
5. Inputs update into the Attributes in Snapshot 2.
6. Launch Analysis. 
7. Get the below error.
![image](https://user-images.githubusercontent.com/43828038/56428072-17750800-628c-11e9-85df-ddd04731db97.png)
8. Troubleshoot: Download the json file from the Terra Tool UI and it shows the variables from Snapshot 1 that were deleted in Snapshot 2. They do not appear in the UI but they are still in the inputs.json file when its downloaded.

9. Workaround: Create a new Tool that represents Snapshot 2 in order to launch analysis. A new Tool for each snapshot.

ZD [#1686](https://broadinstitute.zendesk.com/agent/tickets/1686)

**Comment by panentheos** [comment]
This was fixed, changing the snapshot now correctly removes inputs and outputs that are no longer present.
