### ISSUE TITLE
"Error Loading Clusters" repeatedly appears when no cluster ever created in user account

### ISSUE THREAD

**Issue by schaluva** [DataBiosphere/terra-ui#1466]
A new user who has used Terra for just 1-2 days during Hackathon saw an Error Loading Clusters pop-up each time he refreshed. He had never started a cluster and was a brand new Terra user. The message cannot be permanently disabled either. The issue persisted even after a refresh and a sign-in/out. 
Why is he getting it and can he be able to permanently dismiss it?

![image](https://user-images.githubusercontent.com/43828038/56428346-05e03000-628d-11e9-8358-36cc41effbde.png)

ZD [#1673](https://broadinstitute.zendesk.com/agent/tickets/1673)

**Comment by katevoss** [comment]
I think this is an issue for the Leo team, we're just passing along an error that the user is getting. Despite the fact that this user hasn't created a cluster, we poll to check if the user has any clusters. And if Leo is down, then they'll get this error. I'm not sure why this user kept getting that error though.

**Comment by schaluva** [comment]
@katevoss I can pass it along to the Leo team! Thanks.

**Comment by katevoss** [comment]
@schaluva if this was indeed an issue for the Leo team, I'll close this one.

**Comment by schaluva** [comment]
@katevoss Yes, I passed the ticket and details to Leo and Adrian said he would have someone on his team look at it! Thanks
