### ISSUE TITLE
Maintenance Alert Banners for after the redirect.

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1469]
We need the ability to announce planned maintenance outages and acknowledge unplanned service disruptions directly in the app, such that customer success can apply these as needed.
FireCloud puts up a non-dismissable yellow or red banner for these things respectively (similar to the free credits banner), where multiple banners stack.

We should replicate the process for CS providing text and applying one of these alerts (placing a file in a bucket?)

We can explore alternative display options rather than a banner. One suggestion is to display this as a user-dismissable toast. It should return on refresh or new visit to the site. It should not continue to pop up at a polling interval during a single session.

**Comment by elizzhao** [comment]
Alert notifications were added from mob programming on it and closing the PR. One final detail remains that is referenced here: https://github.com/DataBiosphere/terra-ui/issues/1569 but the bulk of the work is done and merged in.

**Comment by elizzhao** [comment]
Closed since any follow-on work was documented in a separate ticket
