### ISSUE TITLE
Rawls queue status

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1478]
If you're in FireCloud and you're at the monitor tab, you see a queue status with three pieces of info: 
- estimated wait time
- # workflows ahead of yours
- queue status

We should add this on submissions details page. Any pages in this tab should list this. 

AC: User sees option to query queue status from job history & submissions detail page.

**Comment by kleighwe** [comment]
@bradtaylor will add screenshot.

**Comment by breilly2** [comment]
Release notes: Queue status is available in Terra as it was in FireCloud

(or something like that... I'm not great with this wording)

**Comment by schaluva** [comment]
Could I get a screenshot of this? Not sure where in the UI I should be able to see this.

**Comment by tmm211** [comment]
Got it!
