### ISSUE TITLE
Uploading Pair Metadata doesn't create links to case and control samples

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1483]
https://broadinstitute.zendesk.com/hc/en-us/community/posts/360043157771-Uploading-Pair-Metadata-doesn-t-create-links-to-case-and-control-samples

Potential solution: Look at logic differences between FC & Terra.

**Comment by breilly2** [comment]
FireCloud uses the FireCloud data model which is defined by a schema that includes entity types for participant, sample, pair, and sets of those types. Sample and pair have (required) entity reference attributes. These result in a stronger entity reference than a simple string containing the ID of the other entity. FireCloud UI somehow recognizes entity reference columns and renders them as links when displaying workspace data.

Terra uses the "flexible" data model which has no predefined schema. It supports sets through use of a naming convention and does not support for entity references. Also, Terra does not recognize entity reference columns and simply displays the referenced entity's ID as if it were simply a string.

Fixing this will require some work in fc-orch after some consideration of trade-offs. Handling some entity types differently will be inconsistent and could cause confusion for people who do not need the FireCloud data model.

(attn: @bradtaylor)

**Comment by zarsky-broad** [comment]
Could we have a little option when uploading data in the UI that says "use FC data model" or something with an explanation?

**Comment by breilly2** [comment]
We sure could... and we could even set the option default based on firecloud.terra.bio vs app.terra.bio.

**Comment by schaluva** [comment]
I just tried to upload participants, samples, and then pair with the same rules as applied in FC and clicked the button in Terra when uploading "Create participant, sample, and pair associations.." and it still is not linking. Can I get some help determining if I am doing this wrong or if this is not working correctly? I checked in FC after uploading the .tsv files in Terra and it seems to link fine there. 

My steps:
1. upload participant .tsv. check the box to do associations
2. upload sample .tsv with participant column and check associations box.
3. upload pair .tsv with case_sample, control_sample, and participant columns and check associations box.

No links were generated in my Data Model. Users are seeing that Tools that require pair linking etc are failing.

**Comment by breilly2** [comment]
The Terra UI doesn't show these as "links" in the hypertext sense the way
that the legacy FC UI does. If FC is showing the links then the data is
correctly "linked" together in the database.

If users are still seeing problems then either there's a bug in the Terra
UI or, more likely, the data needs to be re-imported now that the Terra UI
supports creating these links.

I can try to set up a test to verify that there isn't a bug in Terra UI. Do
you know of any user workspaces shared with the support team where users
are still seeing this problem?
