### ISSUE TITLE
When a notebook is opened, make it easier to return to the notebook list

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/terra-ui#1488]
When I have a notebook opened in Jupyter in Terra, I don't find anything in the UI to return me to the Notebooks list (other than the back button). I typically click on the Workspace name in the bar at the top and then click on Notebooks again. It would be great if at least "Notebooks" at the top would return me to the Notebooks list.

Thanks!

**Comment by zarsky-broad** [comment]
The notebooks breadcrumb is now clickable.

**Comment by mbookman** [comment]
I like it!
