### ISSUE TITLE
Search Workspace Tags

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1490]
Firecloud has the notion of a user-defineable tag to make searching workspaces easier. Tags are a reserved namespace on workspace attributes. We should implement with AND functionality. 

Note: the endpoint "get all tags" exists.

We should do what FireCloud does. :)

AC: A user can search workspaces via tags.

**Comment by katevoss** [comment]
from #1477:
AC: A user can search workspaces via tags. (Tags should be AND, the endpoint "get all tags" exists.) (1)

**Comment by elizzhao** [comment]
Added filtering by workspace tags, closed by PR #1517
