### ISSUE TITLE
Separate status and controls in job history

### ISSUE THREAD

**Issue by elizzhao** [DataBiosphere/terra-ui#1511]
We have a lot going on in the status column on the job history tab. Let's split it out into "status" and "controls" where items in status give information to the user about the status of their workflows and controls are where a user can interact with the workflow ( aborting, re-running, etc.) 

Here's a rough whiteboard sketch of what it could look like: 
![IMG_4596.JPG](https://images.zenhubusercontent.com/5b7316806a9450578ab01159/902b4e46-ee46-474d-9cd8-939b159562a2)

**Comment by bradtaylor** [comment]
Jerome approves the whiteboard sketch. He can collaborate with the engineer working on it.
Possible controls:
Abort (running workflows)
Relaunch Failures
Check queue status (submitted workflows)

**Comment by elizzhao** [comment]
Closed via connected PR
