### ISSUE TITLE
Simplifying color scheme

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1513]
As an engineer, I need an easy way to implement varying brand color schemes. This involves simplifying our existing color scheme. This will also make my Users & Product Manager happy. :) 

Potential second ticket: applying the simplified color scheme. 

AC: New color scheme (via Lou) is implemented. 
Dependencies: Designs from Lou
Risks/questions: 

Thoughts from Isaac: 
- We'll have highly saturated base colors with an amount of alpha. Instead of implementing as alpha, we should look for a javascript thing that will give us back a hex. @zarsky-broad will add details. `colors.primary(0.5)`

**Comment by kleighwe** [comment]
@lstrano-broad can you link the designs here?

**Comment by lstrano-broad** [comment]
All set - new screens uploaded....
https://invis.io/RTQ5TOUH8FB

New Styleguide....
https://invis.io/P9Q8D68VG8U

**Comment by zarsky-broad** [comment]
Inspect links, for implementation:
[screens](https://projects.invisionapp.com/d/main#/console/16427254/342689700/inspect) and [style guide](https://projects.invisionapp.com/d/main#/console/16427254/342689700/inspect)

If you can't access these, ask @lstrano-broad
