### ISSUE TITLE
Broken links to jobs

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/terra-ui#1529]
Today, there are 2 reasons for why workflow IDs don't exist for all parts of a submission:
1. The workflow submission failed, and hence no UUID.
2. There is latency in the engine due to load, so there are a few seconds before a workflow ID exists.

In both cases, when looking at the submission details view, clicking on the link "View" leads to a dead link: `<job-manager-url>/?jobs/undefined` << which is fairly confusing. Can we add logic to make the "View" button either grayed out or clear out when there is no corresponding Workflow UUID?

**Comment by aednichols** [comment]
+1 just ran into this and briefly freaked out

**Comment by aednichols** [comment]
![Screen Shot 2019-05-03 at 4 43 01 PM](https://user-images.githubusercontent.com/1087943/57164630-b3d9f700-6dc2-11e9-90b2-2d49ed02e412.png)

**Comment by schaluva** [comment]
Seeing this with another user:
<img width="1406" alt="Screen Shot 2019-05-10 at 10 37 07 AM" src="https://user-images.githubusercontent.com/43828038/57535124-97ccdd00-730f-11e9-9b35-612537f647bf.png">

**Comment by bradtaylor** [comment]
@panentheos what's the state of this
