### ISSUE TITLE
Paths to google buckets in workspace data show up as links when they aren't

### ISSUE THREAD

**Issue by seanhorgan** [DataBiosphere/terra-ui#1548]
I took this screenshot from an AMP-PD workspace where the "Workspace Data" section displays values that are references to google storage buckets as clickable links. Most users will expect a clickable link to resolve to the content.

![Screen Shot 2019-05-03 at 4.09.09 PM.png](https://images.zenhubusercontent.com/5a9878524b5806bc2bc909f7/3c93b35a-274d-4ee0-8350-64453578ed45)

![Screen Shot 2019-05-03 at 4.12.42 PM.png](https://images.zenhubusercontent.com/5a9878524b5806bc2bc909f7/5e65cff1-73e2-4872-ad25-8a090e85231f)

**Comment by bradtaylor** [comment]
@seanhorgan, this should resolve to the content. It appears that these objects either do not exist or you lack access to them. The object names are potentially an issue- do the links there begin with gs://_bucketname_/... ?

**Comment by bradtaylor** [comment]
I am going to close this as 'invalid' for now, as the issue appears to be with the content rather than a bug in the system. @seanhorgan Please re-open if you believe this not to be the case
