### ISSUE TITLE
Parameterize colors

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/terra-ui#1564]
Based on our new simplified color scheme per #1513 , we wish to parameterize our color set by URL to support white label branded Terra variants. One such variant is NHLBI DataStage:
https://projects.invisionapp.com/d/main#/console/17337036/359548691/preview

AC
Alternate URLs result in application of an alternate color palate

Dependencies
Labeled color palate (primary, accent, etc) from design resulting from #1513 
Engineers need access to DataStage Invision mocks

**Comment by zarsky-broad** [comment]
Closing in favor of #1513, since we don't have new colors ready.
