### ISSUE TITLE
Running a tool on a Sample Set launches only one job. 

### ISSUE THREAD

**Issue by wnojopra** [DataBiosphere/terra-ui#1583]
I want to launch a tool over several samples. When launching a tool, there is a dropdown after "Process multiple workflows from:" . I can either choose: 
a) Sample Set -> Select data
b) Sample -> Select data -> Choose an existing set

Either choice seems to be correct, but I notice choice A doesn't actually get the samples as input. Instead, it seems to use the single 'sample set' object as the input.

Choice B seems to behave correctly.

![Screenshot 2019-05-09 at 10 41 01 AM](https://user-images.githubusercontent.com/6879774/57464137-3262e880-724a-11e9-8068-9bdc091e7707.png)

In the above screenshot, the second column indicates the same sample set. The first row was using choice B. The second two rows was using choice A.

**Comment by breilly2** [comment]
This is as designed. There are cases (though perhaps rare) where the analysis needs to consider multiple samples at the same time. There is some general agreement that there is work to be done to make the options easier to understand.

**Comment by wnojopra** [comment]
Thanks @breilly2 ! Its a bit confusing but I now understand that choice A is actually passing in the Sample Set entity as the input.
