### ISSUE TITLE
Cleanup the lefthand nav

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/terra-ui#1605]
The lefthand nave is getting a bit full. We want to organize the content a little better by grouping related items under dropdowns. Right now, this means the library and support links. 

For library, we want to roll datasets, showcase/tutorials, and code&tools up into a dropdown, similar to the one for the user profile.

For support, we want to move "contact us" to the bottom and change some of the headings slightly:
Terra Support (new heading, with a question mark icon)
How-to Guides (Was "learn about terra")
Request a Feature
Community Forum (Was "community discussion)
Contact Us

In all cases, items we move under a dropdown should lose their icons (we have too many icons floating around).

These changes are called out in the mocks. See the following screenshot:
![new_lefthand.png](https://images.zenhubusercontent.com/5a6a39f34b5806bc2bc45274/f6fe7227-c06c-4c66-9a38-bcab481dfedf)

Note the removal of the alt color on the profile view, and the introduction of subtle lines. I don't want to mess with the ordering of items at this time.

**Comment by seanhorgan** [comment]
Thanks for creating this issue Brad.

Users who don't run workflows will not need Job Manager. Can we reposition this in the left hand nav so it's not right below workspaces? For most users, it seems like it would be less relevant than the Terra Library, so below that seems appropriate (if we are organizing these top/bottom by relevance).

What is "Home"?

**Comment by seanhorgan** [comment]
Within the Library section, the current order is 
* Datasets
* Showcase & Tutorials
* Code & Tools.

This reflects the left-right order of the library nav (https://app.terra.bio/#library/datasets).

I recommend renaming and reorganizing as:
1. Data. Dataset is the name of a specific collection of assets in Data Repo so we should not use that term to refer to our library of data, which will include the Data Repos along with Gen3 and other repositories. 
2. Tools. By saying "Tools & Code", we imply that they are distinct elements but not everyone thinks along those lines. I think we should keep it simple in the nav and use less terms.
3. Showcase. The presence of "& Tutorials" conflicts with the tutorials we are building in zendesk. 

I prefer the order of Data => Tools => Showcase as the Showcase is the integration of Data & Tools, so it's Data => Tools => Data + Tools.
