### ISSUE TITLE
Errors adding a billing project

### ISSUE THREAD

**Issue by seanhorgan** [DataBiosphere/terra-ui#1614]
When logged in as seanhorgan@google.com, I get the following error when I try to add a new billing project (click on the New button):

![image](https://user-images.githubusercontent.com/428857/57786072-c2150500-772a-11e9-8296-b91954db11de.png)

**Comment by seanhorgan** [comment]
IIRC, I was able to add billing projects in Firecloud. I'm not 100% sure though but I wanted to highlight in case something has changed.

**Comment by bradtaylor** [comment]
Is it possible you declined to grant us the scopes to view billing accounts associated with your google identity?

If not, are you running a privacy blocker that may be interfering?

**Comment by seanhorgan** [comment]
Disregard. The 3 billing projects I have ownership with my google account were all created for me by someone else. I've only been able to create billing projects using my personal account (seanhorgan@gmail.com) and I just confirmed that all is working properly with that.
