### ISSUE TITLE
Cut off long workspace names gracefully

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/terra-ui#1616]
A workspace name can be up to 254 characters long, and in many places we don't visually display it very well.

Workspace list:
card
<img width="301" alt="Screen Shot 2019-05-15 at 11 50 46 AM" src="https://user-images.githubusercontent.com/2395211/57789875-bfed7f00-7707-11e9-864c-004ae69d4680.png">

list
<img width="1308" alt="Screen Shot 2019-05-15 at 11 51 00 AM" src="https://user-images.githubusercontent.com/2395211/57789880-c24fd900-7707-11e9-9737-7653f9f950db.png">

Workspace summary:
<img width="1680" alt="Screen Shot 2019-05-15 at 11 51 34 AM" src="https://user-images.githubusercontent.com/2395211/57789979-e4495b80-7707-11e9-9e24-4b9e18fc5da8.png">

Workspace notebooks:
<img width="1680" alt="Screen Shot 2019-05-15 at 11 51 42 AM" src="https://user-images.githubusercontent.com/2395211/57789925-d4ca1280-7707-11e9-9e39-599668843e00.png">

AC:
- long workspace names are visually handled well so they don't break the design

**Comment by bradtaylor** [comment]
Let's handle this as an AC on Jerome's proposed updates to the workspace list
