### ISSUE TITLE
Scroll notebooks in workspace summary

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/terra-ui#710]
In the summary page for a workspace, there is a scrolling view of notebooks in that workspace. AoU has recently implemented this so we should sync with them for the logic. 

Mock up:
<img width="1244" alt="screen shot 2018-09-27 at 1 34 29 pm" src="https://user-images.githubusercontent.com/2395211/46163754-05813880-c25a-11e8-93c8-86a409d042e1.png">

https://projects.invisionapp.com/d/#/console/13746874/286545629/preview

**Comment by bradtaylor** [comment]
We have more than just notebooks. I believe @lstrano-broad had designs for the summary that included affordances for finding data, running workflows (finding a workflow if you don't have any), and running notebooks (creating one if you don't have any).

I'd like to revisit this later in the Q as we think through our top level nav. First we should build out the code searching portion of the app.

**Comment by panentheos** [comment]
This is based on old mocks and is no longer relevant. Closing.
