### ISSUE TITLE
Add a link to the documentation knowledgebase

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/terra-ui#737]
Communications is using Zendesk to power it's knowledgebase of documentation. See Brad or Geraldine for the current Zendesk rollout plan.

While we ultimately want to embed support materials throughout the app as users explore, the quickest way to give users access to the knowledgebase documentation would be to link to it directly.

Likely, this is from the lefthand nav, though that's up to design :)

**Comment by bradtaylor** [comment]
Issue is blocked on the rollout of the zendesk knowledgebase. Contact Geraldine or Robert for updates to the status of this effort.

**Comment by bradtaylor** [comment]
It should read "Documentation" with a book icon.
I'm just going to say this is in the lefthand nav under settings and "contact us" See here: https://projects.invisionapp.com/d/main#/console/13746874/286545633/preview
...where it would replace "terminal"

**Comment by katevoss** [comment]
I believe this is now complete with the links to Terra Support in #1245
