### ISSUE TITLE
Display submission cost in Job History

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/terra-ui#775]
Users want to know how much they spent on cloud analyses.

FireCloud displays the sum total cost of all the workflows for a submissions on its submission details page. See, for example, the $4.23 incurred here:
https://portal.firecloud.org/#workspaces/help-gatk/five-dollar-genome-analysis-pipeline/monitor/88bba9ee-ce37-424a-829d-49f5a939746b

We should display this for each submission in the Job History tab. Note costs can sometimes take up to a day to populate, and some cannot be displayed. FireCloud has little informational hints letting users know this.

**Comment by bradtaylor** [comment]
We suspect cost is not a field being returned by the submissions endpoint. It's the sum of the workflow costs.

When we call submissions, do we get the full list of workflows, such that we could do the math ourselves?

**Comment by bradtaylor** [comment]
First step is scoping out an approach and a level of effort. Is this a dragon? Maybe! Right now it's an egg. Let's find out what's inside!

**Comment by MattPutnam** [comment]
We don't get workflow detail information, including cost, on the main "get all submissions" endpoint. You only get that on the "get submission details" endpoint.

**Comment by panentheos** [comment]
Based on the above info, this needs some additional thinking before we can implement. If we want to surface this info for all submissions, we probably need the backend to denormalize and store this info at the submission level.

**Comment by bradtaylor** [comment]
We rolled this out when we added a submissions detail view. That is sufficient so that it does not need to be at the top level
