### ISSUE TITLE
Notebook name chopped

### ISSUE THREAD

**Issue by seanhorgan** [DataBiosphere/terra-ui#880]
Notebook names get chopped in the cards view to just ~18 characters. Given the amount of real estate available in the card, it seems like we have more room here to work with.
 
![screenshot 2018-11-16 at 11 44 19 am](https://user-images.githubusercontent.com/428857/48635062-1a926200-e995-11e8-871b-74bcae224c6d.png)

**Comment by zarsky-broad** [comment]
@bradtaylor is this still a concern with the current design that's live?

**Comment by panentheos** [comment]
This is no longer an issue, closing.
