### ISSUE TITLE
Not clear whom to contact to get write access to a workspace

### ISSUE THREAD

**Issue by seanhorgan** [DataBiosphere/terra-ui#881]
I have reader access to a workspace but I need the ability to execute a particular notebook. I don't want to copy the notebook to a new workspace as I don't plan to make any edits. I'd like to contact the owner to ask for the appropriate permission. I couldn't find it in the workspace info page, which is the first place I looked.

![screenshot 2018-11-16 at 11 49 33 am](https://user-images.githubusercontent.com/428857/48635298-c045d100-e995-11e8-82c5-b17f3dc4fca8.png)

**Comment by bradtaylor** [comment]
We're going to handle this per #410. We're just blocked on sam phase IV at the moment, which should be completed by end of quarter.

We could show workspace owner info in the meantime. There's some related work around allowing workspace owners to choose the contact (perhaps a group)

**Comment by katevoss** [comment]
I believe this will be covered by #1485 , is that correct?

**Comment by breilly2** [comment]
Not really. #1485 is specifically about authorization domains whereas this is about permissions for someone who already has access.

**Comment by zarsky-broad** [comment]
Closing as duplicate; we're creating a ticket to show workspace owners directly on the workspace dashboard.
