### ISSUE TITLE
Minor table improvements

### ISSUE THREAD

**Issue by andy7i** [DataBiosphere/terra-ui#906]
#### Copying tsv table to clipboard uses spaces as the delimiter

Not sure if this is intentional, but when a user copies a table of tsv to clipboard, it uses spaces as the delimiter instead of tabs. 

![Screen Shot 2018-11-21 at 6.49.36 PM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/4cef1c82-9283-43b4-8d31-b8d70734161e)

#### On "skinny" tables, the gear icon is far away from the table

![Screen Shot 2018-11-21 at 6.52.57 PM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/5a81973e-bef6-4f44-8535-066ff1cf6f29)

#### The gear icon should have a label, like "Columns"
More obvious than the gear icon alone. 

#### Not always obvious when the table is wider than the screen width
Maybe not quite a minor change. Users might miss data if they don't realize there's more if they scroll right. This could happen especially if the last visible column looks like the last column. One option might be to "fade out" the table if it's not the end. 

![Screen Shot 2018-11-24 at 5.30.16 AM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/8b487064-846c-4fc8-93e3-942cd4d0aaca)

#### "Sort: reset" is actually more like "Sort: alphabetical"
The table/column sorting modal says "Sort: reset", which sounds like it would reset the columns to the prior or initial order, but it actually sorts alphabetically. I think we could say "Sort: alphabetical" or something to that effect to be more clear. Or reset it to the order that existed when the table was generated. Or both?

 ![Screen Shot 2018-11-21 at 7.01.41 PM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/61894931-8150-43fa-9792-6c71935272ac)

#### Nitpick: Grammar when deleting one line
"1 data entries to be deleted."

**Comment by panentheos** [comment]
> Copying tsv table to clipboard uses spaces as the delimiter

Could not reproduce this

> On "skinny" tables, the gear icon is far away from the table

This is due to the virtual table rendering, and would not be straightforward to fix

> Not always obvious when the table is wider than the screen width

This would be a substantial change, not doing this for now

> The gear icon should have a label, like "Columns"
> Nitpick: Grammar when deleting one line
> "Sort: reset" is actually more like "Sort: alphabetical"

Will fix
