### ISSUE TITLE
Open terminal in new tab/pop-up

### ISSUE THREAD

**Issue by elizzhao** [DataBiosphere/terra-ui#992]
While speaking with Alisha Manning on the notebook kernel disconnect issue, she brought up that having the terminal replace the notebook window without any indicator that you were about to leave the notebook was quite disruptive. When pressing the back button, it reloads the notebook again so the user has to wait a little bit which was annoying. 

She expressed that it would be nice if the terminal opened in a new tab or opened as a little window where you could interact with it without it disrupting the work you were doing in the notebook.

**Comment by elizzhao** [comment]
Let's do new tab for now!

**Comment by zarsky-broad** [comment]
@bradtaylor we should re-assess this now that jupyterlab is live, since I expect anyone using it to just open a terminal tab in that, and this could cause more confusion from the behavior change than it fixes.

**Comment by bradtaylor** [comment]
JupyterLab is not ready. We should support Terminal as it's own top level thing. Some people don't want all the jupyter fufera around it. They just want a terminal akin to cloud shell. We should not be opening it over the notebook based on user feedback.
